spring:
  application:
    name: vacation-backend

clickup:
  api:
    tokens:
      - ${CLICK_UP_API_TOKEN}
  list:
    devs: "180311895"

vacation:
  lists:
    180311910:
      start_date: "58004edd-d04c-4edb-bed8-f6337397fd72"
      end_date: "879e67e3-eb65-45eb-9a82-94ac94470918"
      employee_profile_id: "856d3fd6-b982-4085-aa67-65d60bf41bb7"
profile:
  lists:
    180311895:
      egar_id: "836c9684-0c71-4714-aff2-900b0ded0685"
      vacation_list_id: "856d3fd6-b982-4085-aa67-65d60bf41bb7"
      vacation_list: 180311910

org_structure:
  list_id: 204546384
  cu_egar_id: "3ccda2f7-5228-4ce1-b6f7-3f37a3056330"
  lastname: "6efec6e2-1645-49d4-973b-8a15f93c407e"
  firstname: "4caa94ed-8bee-422f-8c35-088faf321fba"
  patronymic: "f73b08e3-03f2-4c8b-9d27-84347daa716a"
  avatar: "d01ad323-e69b-4413-9d57-256613e62ee0"
  root_task_org_struct: "2vj3zgb"


